APPLICATION1/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'APPLICATION1'
urlpatterns = [
    path('', views.home, name="home"),
    path('loginview/<int:logged_student_id>/', views.loginview, name="loginview"),
    path('borrow/<int:logged_student_id>/', views.borrow, name="borrow"),
     path('borrowed/', views.borrowed, name="borrowed"),
    path('checkout/', views.checkout, name="checkout"),
    path('signup', views.signup, name="signup"),
    path('signin', views.Student.login, name="signin"),
    path('signout', views.signout, name="signout"),
    path('about', views.About, name="About"),
    path('bookrequest/', views.bookrequest, name='bookrequest'),
    path('booklister', views.booklister, name='booklister'),
    path('libsearch/', views.libsearch, name='libsearch'),
]

BOOK_MANAGEMENT/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('APPLICATION1.urls')),
    path('', include('libralian.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

libralian/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'libralian'
urlpatterns = [
    path('library', views.library, name='library'),
    path('approve', views.approve, name='approve'),
    path('bookreturn', views.bookreturn, name='bookreturn'),
    path('fine', views.fine, name='fine'),
    path('signout', views.signout, name='signout'),
    path('newbook', views.newbook, name='newbook'),
]

APPLICATION1/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from django.utils import timezone
from datetime import date, datetime, timedelta

class Book(models.Model):
    title = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    status = models.CharField(max_length=13, default="Available")
    category = models.CharField(max_length=20, null=True)
    bookcover=models.ImageField()
    description = models.TextField(null=True, blank=True)

class BookedBook(models.Model):
    book_id = models.IntegerField(null=True)
    title = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    category = models.CharField(max_length=20, null=True)
    bookcover=models.ImageField()
    user_name = models.CharField(max_length=50)
    student_id = models.IntegerField()
    booking_start = models.DateTimeField(default=datetime.today())
    booking_end = models.DateTimeField(default=datetime.today()+timedelta(days=4))
     
class Student(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    user_name = models.CharField(max_length=50)

    def __str__(self):
        return self.first_name


class BookRequest(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    req_date = models.DateField('Date of book request', null=True, blank=True)
    #return_date = req_date + datetime.timedelta(days=8) 
    book_id = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return self.book_id

class Fines(models.Model):
    book_id = models.IntegerField()
    student_id = models.IntegerField()
    actual_return_date = models.DateField()
    extra_days = models.IntegerField()
    fine = models.IntegerField()

APPLICATION1/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from . models import Book, BookedBook
from django.urls import reverse
import time
from django.utils import timezone
from datetime import date, datetime, timedelta

def home(request):
    context = {}
    return render(request, "authentication/index.html", context)

def booklister(request):
    info = []
    if request.method == 'POST':
        data = request.POST.items()
        info = list(data)
        print(info)
        logged_student_id = info[1][1]
    return HttpResponseRedirect(reverse('APPLICATION1:borrow', args=(logged_student_id,)))


def borrow(request, logged_student_id):
    new_books = Book.objects.order_by('title')[:]
    student_id = logged_student_id
    context = {'new_books': new_books, 'student_id': student_id}
    return render(request, "authentication/borrow.html", context)

def borrowed(request):
    student_id = request.session['student_id']
    context = {'student_id': student_id}
    return render(request, "authentication/borrowed.html", context)

def checkout(request):
    student_id = request.session['student_id']
    context = {'student_id': student_id}
    return render(request, "authentication/checkout.html", context)

def signup(request):
    if request.method == "POST":
        username = request.POST['username']
        fname = request.POST['fname']
        lname = request.POST['lname']
        email = request.POST['email']
        pass1 = request.POST['pass1']
        pass2 = request.POST['pass2']

        if User.objects.filter(username=username):
            messages.error(request, "Username already exists! Please try another Username")
            return redirect('APPLICATION1:home')

        if User.objects.filter(email=email):
            messages.error(request, "Email already registered!")
            return redirect('APPLICATION1:home')
        
        if len(username)>10:
            messages.error(request, "Username must have only 10 characters")
        
        if pass1 != pass2:
            messages.error(request, "Passwords don't match!")

        if not username.isalnum():
            messages.error(request, "Username should be Alpha-Numeric!")
            return redirect('home')

        myuser = User.objects.create_user(username, email, pass1)
        myuser.first_name = fname
        myuser.last_name = lname

        myuser.save()

        return redirect('APPLICATION1:signin')



    return render(request, "authentication/signup.html")

def signin(request):
    request.session['student_id'] = ""
    if request.method =='POST':
        username = request.POST['username']
        pass1 = request.POST['pass1']
        logged_student_id = None

        user = authenticate(username=username, password=pass1)

        if user is not None:
            if user.is_staff:
                return HttpResponseRedirect(reverse('libralian:library')) 
            else:
                login(request, user)
                fname = user.first_name
                logged_student = User.objects.get(username=username)
                logged_student_id = logged_student.id
                request.session['student_id'] = logged_student_id
                return HttpResponseRedirect(reverse('APPLICATION1:loginview', args=(logged_student_id,))) 
                
        else:
            messages.error(request, "Invalid Credentials!")
            return redirect('APPLICATION1:home')

    return render(request, "authentication/signin.html")

def signout(request):
    logout(request)
    messages.success(request, "Logged Out Successfully")
    return redirect('APPLICATION1:home')

def About(request):
    student_id = request.session['student_id']
    context = {'student_id': student_id}
    return render(request, "authentication/about.html", context)

def loginview(request, logged_student_id):
    context = {'student_id': logged_student_id}
    return render(request, "authentication/loginview.html", context)

def bookrequest(request):
    info = []
    already_booked = ""
    borrow_once = ""
    today = date.today()
    return_date = datetime.today() + timedelta(days=4)
    if request.method == 'POST':
        data = request.POST.items()
        info = list(data)
        book_id = info[1][1]
        request.session['book_id'] = book_id
        student_id = info[2][1]
        book = Book.objects.get(id=book_id)
        student = User.objects.get(id=student_id)
        try:
            booker = BookedBook.objects.get(student_id=student_id)
            borrow_once = "You already have a pending bookrequest and only a single book can be requested at a time."
        except BookedBook.DoesNotExist:
            try:
                booked_checker = BookedBook.objects.get(book_id=book_id)
                already_booked = "Book already Booked, Please choose another copy or wait until it's returned"
            except BookedBook.DoesNotExist:
                current = timezone.now() 
                book.status = "Booked"
                book.save()
                booked = BookedBook.objects.create(book_id=book_id,title=book.title,author=book.author,category=book.category,  bookcover=book.bookcover,user_name=student.username,student_id=student_id,booking_start=current)
                booked.save()
        context = {'book':book, 'student_id': student_id, 'already_booked':already_booked, 'borrow_once':borrow_once, 'today': today, 'return_date': return_date}
    return render(request, 'authentication/checkout.html', context)

def libsearch(request):
    info = []
    empty_search = "Sorry, Book Not Found!"
    student_id = request.session['student_id']
    if request.method == 'POST':
        data = request.POST.items()
        info = list(data)
        search_text = info[1][1]
        search_title = Book.objects.filter(title__icontains=search_text)
        search_author = Book.objects.filter(author__icontains=search_text)
        search_status = Book.objects.filter(status__icontains=search_text)
        search_category = Book.objects.filter(category__icontains=search_text)

        if search_title:
            search_results = search_title
        elif search_author:
            search_results = search_author
        elif search_status:
            search_results = search_status
        elif search_category:
            search_results = search_category 
        else:
            search_results = empty_search
    return render(request, 'authentication/searchresults.html', {'search_results':search_results, 'empty_search': 
    empty_search, 'student_id': student_id})

class Student:
    login = signin

APPLICATION1/templates/APPLICATION1/about.html
{% extends 'APPLICATION1/main.html'%}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

</head>
<body>
    <h2>ABOUT US</h2>
    <p>Welcome to Web Lib,your number one source for all the books of your interest.We're
        dedicated to providing you the very best of the library services that may include borrowing books ,exhibation
        of some up raising writers and promote Education at most in the society.
         </p>
         <p1>This application was founded in 2022 by team of software developers with the aim of easing 
             the library management system in physical terms as it was complicated in managing in a large
             society.
         </p1>
         <p>  * TheWeb Lib enables the session of reading any book of your choice in a given duration by
                 by the system . </p>
         <p>  * In this system the user can borrow a book after clicking on the on the borrowing option.
              The User's crediantals are taken and the User is given a duration on when to return
              the book so as that it can be available for others. Failure to return the book,the User
              is disabled from accessing the borrowing option and given a penalty on the time the student 
              decides to return the book.  
         </p> 
         <p> Incase more details and help on the system how it operates try to reach us through the following links 
           and we see how we can help you and be able to access our services with ease and comfort.
         </p>
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
</html>
{% endblock content %}

APPLICATION1/templates/APPLICATION1/borrow.html
<!DOCTYPE html>
{% load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Web Library</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">


    <link rel="stylesheet" type="text/css" href="{% static 'APPLICATION1/css/main.css' %}">

    <meta name"viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1"/>
</head>
<body>
    
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#"></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'APPLICATION1:loginview'%}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'APPLICATION1:borrow'%}">Books</a>
          </li><li class="nav-item">
            <a class="nav-link" href="{% url 'APPLICATION1:checkout'%}">checkout</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'APPLICATION1:About'%}">ABOUT US</a>
          </li>
        </ul>
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
        <a href="{% url 'APPLICATION1:borrowed'%}">
          <img id="books-icon" src="/static/images/books.png">
      </a>
      <p id="books-total">0</p>
      </div>
    </div>
  </nav>

    <div class="container">
        {% for Book in new_books %}
            <div class="row">
                <div class="col-md-3 product-men">
                    <img width="250" height="320" src="{{Book.bookcover.url}}">
                    <div class="box-element book-title">
                        <h6><strong>{{ Book.title }}</strong></h6>
                        <p>{{ Book.author }}</p>
                        <hr>
                        <button class="btn btn-outline-secondary add-btn">Add to Borrow</button>
                        <a class="btn btn-outline-success" href="#">View</a>
                        <h4 style="display: inline-block;float: right">0</h4>
                    
                    </div>
                
                </div>
            {% endfor %}
    </div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
    
</body>
</html>

APPLICATION1/templates/APPLICATION1/borrowed.html
{% extends 'APPLICATION1/main.html'%}
{% load static %}
{% block content %}

<div class="row">
    <div class="col-lg-12">
        <div class="box-element">
            <a class="btn btn-outline-dark" href="{% url 'APPLICATION1:borrow' %}">&#x2190; Continue Borrowing</a>

            <br>
            <br>
            <table class="table">
                <tr>
                    <th><h5>Books: <strong>4</strong></h5></th>
                    <th><h5>Plenty: <strong>5,000UGX</strong></h5></th>
                    <th>
                        <a style="float:right; margin:5px" class="btn btn-success" href="{% url 'APPLICATION1:checkout' %}">Checkout</a>
                    </th>
                </tr>

            </table>

        </div>
        <br>
        <div class="box-element">
            <div class="cart-row">
                <div style="flex:2"></div>
                <div style="flex:2"><strong>Book</strong></div>
                <div style="flex:1"><strong>Pickup Date</strong></div>
                <div style="flex:1"><strong>Return Date</strong></div>
                <div style="flex:1"><strong>Plenty</strong></div>
            </div>

            <div class="cart-row">
                <div style="flex:2"><img class="row-image" scr="{% static 'APPLICATION1/images/placeholder.png' %}"></div>
                <div style="flex:2">book 1</div>
                <div style="flex:1">03/07/2022</div>
                <div style="flex:1">08/07/2022</div>
                <div style="flex:1">5000UGX</div>
            </div>

        </div>

    </div>
</div>
    
{% endblock content %}

APPLICATION1/templates/APPLICATION1/checkout.html
{% extends 'APPLICATION1/main.html'%}
{% load static %}
{% block content %}


{% endblock content %}

APPLICATION1/templates/APPLICATION1/index.html
{% load static%}
<link rel="stylesheet" type="text/css" href="{% static 'APPLICATION1/css/main.css' %}">

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Authentication</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

</head>
<body background="image1.jpg">
    {% for message in messages %}
<div class="alert alert-{{ message.tags}} alert-dismissble fade show" role="alert" class="container bg bg-white">
<strong>Message:</strong>{{ message }}
<button type="button" class="close" data-dismiss="alert" aria-label="Close">
<span aria-hidden="true">&times;</span>
</button>
</div>
{% endfor %}
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href=""></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'APPLICATION1:signup'%}">signup</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'APPLICATION1:signin'%}">signin</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
<h1 class="text-center">Welcome to Web Libary</h1>

<p>
    This is a library Management System.<br>
    One can borrow a book and later on return it.They are a multitude of books.<br>
    It helps one in search of a particular book.<br>
    One is Required to sign in.

</p>



    <button class="btn btn-outline-primary" type="submit"><a href="{% url 'APPLICATION1:signup'%}"> SignUp</a></button>
    <button class="btn btn-outline-primary" type="submit"><a href="{% url 'APPLICATION1:signin'%}"> SignIn</a></button>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
</body>
</html>

APPLICATION1/templates/APPLICATION1/loginview.html
{% extends 'APPLICATION1/main.html'%}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>LOGIN PAGE</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

</head>
<body>

  <h1 class="text-center">Welcome to Web Libary</h1>
  {% if user.is_authenticated %}
<h3>Hello {{ fname }}</h3>
<h4>You're successfully logged in.</h4>
   

    {% for message in messages %}
<div class="alert alert-{{ message.tags}} alert-dismissble fade show" role="alert" class="container bg bg-white">
<strong>Message:</strong>{{ message }}
<button type="button" class="close" data-dismiss="alert" aria-label="Close">
<span aria-hidden="true">&times;</span>
</button>
</div>
{% endfor %}

<p>
    This is a library Management System.<br>
    One can borrow a book and later on return it.They are a multitude of books.<br>
    It helps one in search of a particular book.<br>
    One is Required to sign in.
  

</p>
<button class="btn btn-outline-primary"  type="submit"> <a href="/signout"> SignOut</a></button>
{% else %}
{% endif %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
</body>
</html>
{% endblock content %}

APPLICATION1/templates/APPLICATION1/main.html
<!DOCTYPE html>
{% load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Web Library</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">


    <link rel="stylesheet" type="text/css" href="{% static 'APPLICATION1/css/main.css' %}">

    <meta name"viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1"/>
</head>
<body>
    
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#"></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'APPLICATION1:loginview'%}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'APPLICATION1:borrow'%}">Books</a>
          </li><li class="nav-item">
            <a class="nav-link" href="{% url 'APPLICATION1:checkout'%}">checkout</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'APPLICATION1:About'%}">ABOUT US</a>
          </li>
        </ul>
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
        <a href="{% url 'APPLICATION1:borrowed'%}">
          <img id="books-icon" src="/static/images/books.png">
      </a>
      <p id="books-total">0</p>
      </div>
    </div>
  </nav>
  
  <img id="books-icon" src="/static/images/books.png">

    <div class="container">
        {% block content %}

        {% endblock content %}
    </div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
    
</body>
</html>

APPLICATION1/templates/APPLICATION1/signin.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

</head>
<body>

  <div class="position-absolute top-0 start-50 translate-middle"><h3>Sign In</h3></div>

    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href=""></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'APPLICATION1:signup'%}">signup</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'APPLICATION1:signin'%}">signin</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>

<br>
<h3>Sign In</h3>
<div class="position-absolute top-50 start-50 translate-middle">
  <div class="card border-primary mb-3 text-center"  style="max-width: 24rem; ">
    <div class="card-header">SignIn</div>
    <div class="card-body">
      <h5 class="card-title">PLEASE SIGN IN HERE</h5>
      <p class="card-text">
        <form action="{% url 'APPLICATION1:signin'%}" method="post">
          {% csrf_token %}
              <label for="">Username</label>
              <input type="text" id="username" name="username" placeholder="Enter Your Username"Required>
              <br>
              <br>
      
              <label for="">Password</label>
              <input type="password" id="pass1" name="pass1" placeholder="Enter Your Password"Required>
              <br>
              <br>
      
      
              <button type="submit" type="button" class="btn btn-primary">Sign In</button>
          </form>
      </p>
    </div>
  </div>
</div>


     
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
</body>
</body>
</html>